### ISSUE TITLE
get_all_answers()貌似无法处理自己回答

### ISSUE THREAD

**Issue by kehao95** [egrcc/zhihu-python#10]
当某问题下回答包含自己的回答的时候。
Question.get_all_answers()貌似不能抓到自己的回答。
并且当自己的回答排在最后的时候会出错
```Python
    url="http://www.zhihu.com/question/xxxxx"
    Q=Question(url)
    for i in Q.get_all_answers():
		print i.answer_url
```

```Python
Traceback (most recent call last):
  File "/home/kehao/Documents/zhihu-python-master/test.py", line 37, in <module>
    get_a_question()
  File "/home/kehao/Documents/zhihu-python-master/test.py", line 28, in get_a_question
    for i in Q.get_all_answers():
  File "/home/kehao/Documents/zhihu-python-master/zhihu.py", line 188, in get_all_answers
    count = soup.find_all("span", class_="count")[j].string
IndexError: list index out of range
```

**Comment by egrcc** [comment]
确实是bug，感谢反馈

**Comment by egrcc** [comment]
已修复。https://github.com/egrcc/zhihu-python/commit/b756ff88f785fa8815ac8bf1f4137c39f399c6d6
