### ISSUE TITLE
网络异常

### ISSUE THREAD

**Issue by xxllp** [egrcc/zhihu-python#70]
用户失效后重新登录报错：
 `WARN: 网络故障
INFO: 正在加载配置文件 ...
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/��Ӱ/���ݽṹ���㷨/auth.py", line 241, in <module>
    login()
  File "C:/Users/Administrator/PycharmProjects/��Ӱ/���ݽṹ���㷨/auth.py", line 213, in login
    form_data = build_form(account, password)
  File "C:/Users/Administrator/PycharmProjects/��Ӱ/���ݽṹ���㷨/auth.py", line 115, in build_form
    form['_xsrf'] = search_xsrf()
  File "C:/Users/Administrator/PycharmProjects/��Ӱ/���ݽṹ���㷨/auth.py", line 101, in search_xsrf
    raise NetworkError(u"验证码请求失败")
__main__.NetworkError
ERROR: 网络异常
`
这个是网络异常还是登录失败了

**Comment by tzhao0311** [comment]
WARN: 网络故障
INFO: 正在加载配置文件 ...
WARN: 帐号信息无效
请输入登录账号: 

重新登陆也不行，说是网络故障。

**Comment by xxllp** [comment]
啥意思楼上，你也遇到这个问题了吗

**Comment by tzhao0311** [comment]
是的，我也遇到这个问题了，不知道怎么解决呢

**Comment by xxllp** [comment]
第一次还行后面再登录就不行了。

**Comment by luckysteven1983** [comment]
url = 'http://www.zhihu.com'
r = requests.get(url, verify=False)
r.status_code
500
知乎把端口封了？

**Comment by xxllp** [comment]
感觉作者的登录写的比较长

**Comment by eduOS** [comment]
看来被盯上了，我的也失败了，才爬到2006****左右，请问有谁有之后的数据？可不可以传给我一下？谢谢。

**Comment by TPeterW** [comment]
一样的问题，有人有临时fix吗？

**Comment by tzhao0311** [comment]
同求

**Comment by jiongshen1808** [comment]
def search_xsrf():
	url="http://www.zhihu.com/"
	headers={
		'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36", 
		'Host': "www.zhihu.com", 
		'Origin': "http://www.zhihu.com", 
		'Pragma': "no-cache", 
		'Referer': "http://www.zhihu.com/", 
		'X-Requested-With': "XMLHttpRequest" 
	}
	r=requests.get(url,headers=headers)
	if int(r.status_code)!=200:
		raise NetworkError(u'验证码请求失败')
	results=re.compile(r"\<input\stype=\"hidden\"\sname=\"_xsrf\"\svalue=\"(\S+)\"",re.DOTALL).findall(r.text)
	if len(results)<1:
		Logging.info(u"提取XSRF代码失败")
		return None
	return results[0]

**Comment by tzhao0311** [comment]
按照楼上的代码还是出现同样的问题

**Comment by KMKL** [comment]
遇到同样的问题 +1

**Comment by yujunhui** [comment]
大家把auth.py里面的所有request.get都传多一个参数 headers=headers 就能解决问题了，headers能在auth.py里面找到

**Comment by pjpjq** [comment]
楼上什么意思...

**Comment by zzz0906** [comment]
request.get都传多一个参数 headers=headers 正解 
在每一个函数里都添加一个headers 然后传过去就可以了
