### ISSUE TITLE
Answer.get_question()失败

### ISSUE THREAD

**Issue by TPeterW** [egrcc/zhihu-python#74]
错误报告如下，应该是知乎换了格式了
Traceback (most recent call last):
  File "./crawl.py", line 19, in <module>
    print "\nQuestion " + ": " + answer.get_question().get_title() + "\n"
  File "/Users/Peter/Desktop/Palo Alto/zhihu.py", line 1070, in get_question
    question_link = soup.find("h2", class_="zm-item-title zm-editable-content").a
AttributeError: 'NoneType' object has no attribute 'a'

**Comment by yangjiwen** [comment]
修改一下class属性值就行。 class_="zm-item-title"
