### ISSUE TITLE
auth.py验证码请求失败

### ISSUE THREAD

**Issue by star-counter** [egrcc/zhihu-python#78]
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
WARN: 网络故障
ERROR: 网络异常
Traceback (most recent call last):
  File "C:/Users/Administrator/Downloads/zhihu-python-master/zhihu-python-master/auth.py", line 240, in <module>
    login(account="马赛克@qq.com", password="马赛克")
  File "C:/Users/Administrator/Downloads/zhihu-python-master/zhihu-python-master/auth.py", line 213, in login
    form_data = build_form(account, password)
  File "C:/Users/Administrator/Downloads/zhihu-python-master/zhihu-python-master/auth.py", line 115, in build_form
    form['_xsrf'] = search_xsrf()
  File "C:/Users/Administrator/Downloads/zhihu-python-master/zhihu-python-master/auth.py", line 101, in search_xsrf
    raise NetworkError(u"验证码请求失败")
__main__.NetworkError

**Comment by spto** [comment]
咋办

**Comment by star-counter** [comment]
还没找到解决办法，另外没注意可能因为我用的win10？

**Comment by dakabang** [comment]
在requests请求的时候加上headers
`r = requests.get(url, params={"r": random.random(), "type": "login"}, verify=False, headers=headers)`
headers如下：
    `'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"`

**Comment by XiZiler** [comment]
@dakabang That's the point! Thank you~

to be more clear, `headers` should be added in the function `download_captcha`.
