### ISSUE TITLE
爬下来了，但还是会报错

### ISSUE THREAD

**Issue by phoenixg** [egrcc/zhihu-python#9]
这回应该不是我安装的问题啦
````
from zhihu import Question

url = "http://www.zhihu.com/question/29862735"
question = Question(url)
answers = question.get_all_answers()
for answer in answers:
    answer.to_txt()
    answer.to_md()
````

````
root@AY1407131602375Z:~/zhihu-python# python test001.py
Login Failed, reason is:
请填写验证码
Use cookies
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--喻长大的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--喻长大的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--海天的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--海天的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--mu peng的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--mu peng的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--desire caution的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--desire caution的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--清风浅的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--清风浅的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--吴名士的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--吴名士的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--程啸的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--程啸的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--meggie huo的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--meggie huo的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--左牵黄右擎苍的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--左牵黄右擎苍的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--张赞的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--张赞的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--卢百万的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--卢百万的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Jack Nee的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Jack Nee的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--张萌萌blingbling的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--张萌萌blingbling的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--章子晏的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--章子晏的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--鱼吞舟的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--鱼吞舟的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--王粤北的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--王粤北的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--苏昕的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--苏昕的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--William的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--William的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--姜委员长的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--姜委员长的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Richard L的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Richard L的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--周如南的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--周如南的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--此人已失控的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--此人已失控的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--山羊月的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--山羊月的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--路加的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--路加的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--姚泽云的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--姚泽云的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--零崎月光的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--零崎月光的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--胡杨的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--胡杨的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--周大明白的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--周大明白的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--送赞干不的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--送赞干不的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--废了完了算了的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--废了完了算了的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--飞面福音的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--飞面福音的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--克里斯的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--克里斯的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--杨怀斌的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--杨怀斌的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Roland Xu的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Roland Xu的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--很卡的哇伊叔的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--很卡的哇伊叔的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--于经文的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--于经文的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--你们啊就想的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--你们啊就想的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--匿名用户的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--匿名用户的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--yoco的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--yoco的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--云宇的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--云宇的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--富丽的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--富丽的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--凤红邪的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--凤红邪的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--李炜的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--李炜的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--匿名用户的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--匿名用户的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Parasession的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Parasession的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--海小呆的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--海小呆的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Chinito超强的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Chinito超强的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Rice Naomi的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--Rice Naomi的回答.md
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--黄武鹏的回答.txt
为什么没看见神和神迹，还会有 20 亿基督徒，近 40 亿人信仰上帝？--黄武鹏的回答.md
Traceback (most recent call last):
  File "test001.py", line 6, in <module>
    for answer in answers:
  File "/root/zhihu-python/zhihu.py", line 248, in get_all_answers
    answer = soup.find_all("div", class_=" zm-editable-content clearfix")[j]
IndexError: list index out of range

````

**Comment by egrcc** [comment]
嗯，这是一个bug，多谢报告。原因是中间有个答案被和谐了，导致程序出错。等我有空了修复下。

**Comment by egrcc** [comment]
已修复。https://github.com/egrcc/zhihu-python/commit/9b4dd5a3d551bef5e09db550e55fd5f5ae28c137
